# plugin.yml
name: DeWaltCore
version: 1.0
main: com.TNTStudios.deWaltCore.DeWaltCore
api-version: 1.19
author: TuNombre
depend: [Oraxen]

commands:
  empezar:
    description: Inicia el minijuego del laberinto.
  detener:
    description: Detiene el minijuego del laberinto.
  taladro:
    description: Entra al lobby del minijuego del taladro.
  concreto:
    description: Entra al lobby del minijuego del concreto.