name: DeWaltCore
version: '1.0.0'
main: com.TNTStudios.deWaltCore.DeWaltCore
api-version: '1.21'
authors: [ TNTStudios ]
website: https://tntstudiosn.space/
softdepend:
  - DecentHolograms

# --- Comandos Añadidos ---
commands:
  empezar:
    description: Comienza el cronómetro para el laberinto.
    usage: /empezar
  detener:
    description: Detiene el cronómetro y registra tu tiempo en el laberinto.
    usage: /detener