# plugin.yml
name: DeWaltCore
version: 1.0
main: com.TNTStudios.deWaltCore.DeWaltCore
api-version: 1.19
author: TuNombre

commands:
  empezar:
    description: Inicia el minijuego del laberinto.
    usage: /empezar
  detener:
    description: Finaliza el minijuego del laberinto.
    usage: /detener
  # --- MI NUEVO COMANDO ---
  taladro:
    description: Inicia el minijuego del taladro.
    usage: /taladro