name: DeWaltCore
version: '1.0.0'
main: com.TNTStudios.deWaltCore.DeWaltCore
api-version: '1.21'
authors: [ TNTStudios ]
website: https://tntstudiosn.space/
softdepend:
  - DecentHolograms
commands:
  empezar:
    description: Inicia el timer del laberinto
  detener:
    description: Detiene el timer del laberinto
